# Generated by Django 5.2.1 on 2025-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_complete_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='PEDIDO GESTIONADO'),
        ),
    ]
