# Generated by Django 5.2.1 on 2025-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_access_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
