# Generated by Django 5.2.1 on 2025-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
