# Generated by Django 5.2.1 on 2025-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_mensaje_fecha_lectura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título breve de la promoción (ej. 'Envío Gratis')", max_length=100)),
                ('mensaje', models.TextField(help_text="Descripción detallada de la promoción (ej. 'En todos los pedidos superiores a 50€')")),
                ('imagen', models.ImageField(blank=True, help_text='Imagen opcional para la promoción', null=True, upload_to='promociones/')),
                ('url_destino', models.URLField(blank=True, help_text='URL a donde redirigir al hacer clic en la promoción (ej. /store/ofertas-especiales/)', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Marca si esta promoción debe mostrarse en la tienda')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de la promoción (opcional)', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la promoción (opcional)', null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio', 'titulo'],
            },
        ),
    ]
